### ISSUE TITLE
Install MDB(Material Design for Bootstrap)

### ISSUE THREAD

**Issue by gitfullstacker** [chenxidev1129/taskmaster-ui#1]

**Comment by gitfullstacker** [comment]
I attempted to install MDB, but I encountered dependency conflicts. Can I try installing Angular Material instead?

**Comment by johnsmith0305** [comment]
@chenxidev1129 Alright, I agree.

**Comment by johnsmith0305** [comment]
I will close this ticket and create a new ticket to install Angular Material.
