### ISSUE TITLE
Use enhance UI framwork for Angular 17

### ISSUE THREAD

**Issue by gitfullstacker** [chenxidev1129/taskmaster-ui#14]
There are preferred UI frameworks for Angular 17:
Angular Material
PrimeNG
Bootstrap

**Comment by johnsmith0305** [comment]
@chenxidev1129 do you have a preferred platform?

**Comment by gitfullstacker** [comment]
I think **PrimeNG** is good.

**Comment by johnsmith0305** [comment]
okay. you can do
