### ISSUE TITLE
Implement Authentication

### ISSUE THREAD

**Issue by johnsmith0305** [chenxidev1129/taskmaster-ui#16]
Generate components:
- pages/auth/login
- pages/auth/register
- pages/auth/forgot

Generate services:
- AuthService

Generate models:
- login
- register

**Comment by gitfullstacker** [comment]
@johnsmith0305 Are we planning to implement JWT authentication?

**Comment by johnsmith0305** [comment]
Alright, we've already implemented JWT authentication on the ASP.NET Core Web API.

**Comment by gitfullstacker** [comment]
@johnsmith0305 Can I use Tailwind CSS in our project?

**Comment by johnsmith0305** [comment]
Yes
