### ISSUE TITLE
Authentication deisgn update

### ISSUE THREAD

**Issue by gitfullstacker** [chenxidev1129/taskmaster-ui#20]
@johnsmith0305 I believe we should consider updating for these pages:
Login page
Signup page
Forgot password page

**Comment by johnsmith0305** [comment]
@chenxidev1129 Agreed, you can start working the updating of design for these pages. Thank you.

**Comment by kgg0305** [comment]
This issue should be assigned to me?

**Comment by johnsmith0305** [comment]
No, @chenxidev1129 can do it. I will check the another ticket for you, @kgg0305

**Comment by gitfullstacker** [comment]
@johnsmith0305 Could we address the **Forgot Password page** at a later time?

**Comment by johnsmith0305** [comment]
What issue are you encountering?

**Comment by gitfullstacker** [comment]
The backend is not prepared yet.

**Comment by johnsmith0305** [comment]
Sure, go ahead and work on the design first. We can address that functionality later on.
