### ISSUE TITLE
Implement Social Login in Task Management Project

### ISSUE THREAD

**Issue by fullstackdev0305** [chenxidev1129/taskmaster-ui#28]
### Description:
As part of enhancing our task management project, we aim to incorporate social login functionality using the abacritt/angularx-social-login package in the frontend, which is built with Angular.

### Objective:
Enable users to log in via popular social platforms (e.g., Google, Facebook, etc.) to access our task management application.

### Tasks:

1. Integration of abacritt/angularx-social-login:
- Install and set up the abacritt/angularx-social-login package.
- Configure the package to enable login through multiple social platforms.

2. UI Implementation:
- Design and integrate login buttons for each social platform.
- Create UI elements to capture necessary user data from social login.

3. Authentication Flow:
- Implement the authentication flow to handle social login responses.
- Manage user sessions and authentication tokens obtained from social platforms.

### Additional Information:
- Frontend Framework: Angular
- Package Used: abacritt/angularx-social-login
- Endpoints and Backend Integration: Ensure the integration with backend endpoints for user authentication and data handling.

**Comment by gitfullstacker** [comment]
@kgg0305 Please confirm login design for social login(Google and Facebook)
@smartwebdev2023 Please set the environment in Facebook

**Comment by kgg0305** [comment]
Yes 
![image](https://github.com/KGG-Dev-Course/taskmaster-ui/assets/58977491/ebb48b94-cce4-4a23-b35c-d32ca7f17b77)
We can use this Pinterest login design in our project.

**Comment by gitfullstacker** [comment]
okay, How do you think @johnsmith0305

**Comment by johnsmith0305** [comment]
agree
